### ISSUE TITLE
Using Multiple resources crashes chrome

### ISSUE THREAD

**Issue by blanchg** [coinbase/rest-hooks#78] opened 2019-06-12 03:53 UTC
**React version** 16.8.6

**Concurrent mode** no

**Describe the bug**
Passing multiple resources to useResource crashes chrome sometimes

**To Reproduce**
1. Go to https://rest-hooks-w44uh8.stackblitz.io/multiple
2. Click on the menu item multiple
3. Sometimes it will show "10, 11" sometimes the tab will crash
4. Refresh the page, will crash usually within a few refreshes

**Expected behavior**
It shouldn't crash.

Switching to the other method will mean it never crashes
https://stackblitz.com/edit/rest-hooks-w44uh8?file=issues%2FMultipleResources.tsx

**Comment by ntucker** [comment] 2019-06-12 04:23
Thanks for the clear report! I'll look into this immediately.

**Comment by ntucker** [comment] 2019-06-14 01:40
Published https://www.npmjs.com/package/rest-hooks/v/1.6.6-beta.0 with something that might fix. I was unable to reproduce this locally and then I got rate-limited by the github API. Can you check to see if that version works for you @blanchg ? Thanks!

**Comment by blanchg** [comment] 2019-06-14 01:55
@ntucker  Thanks for publishing the beta, I updated the sample above with that new version and it still appears to crash for me.  Chrome 75.0.3770.80 on Windows 10.

**Comment by ntucker** [comment] 2019-06-14 02:04
Gonna retry reproducing at home so I'll have a new IP to avoid rate limit. What I really need is a repo I can clone locally and try changing the rest-hooks library manually to verify fixes. Do you think that's something you can make?

**Comment by blanchg** [comment] 2019-06-14 02:06
Can you just download the stackblitz project and run locally?

**Comment by blanchg** [comment] 2019-06-14 02:08
All it needs is to make two resource calls using the useResource(
[resource1], [resource2] ) format.

**Comment by jjordy** [comment] 2019-06-14 02:12
This seems so similar to what was happening to me on #50, I am still having that issue intermittently but have narrowed it down to opening devtools during a network request. Have you guys noticed anything like this happening? Im wondering if this is related. @ntucker @blanchg

**Comment by blanchg** [comment] 2019-06-14 02:36
If you open the Task Manager in Google Chrome the service worker ends up running at near 100% cpu even after the tab is closed too.

**Comment by ntucker** [comment] 2019-06-14 03:22
Maybe this has something to do with hotreloading?

**Comment by ntucker** [comment] 2019-06-14 16:57
I suspect this has to do with how stackblitz has webworkers loading the service. This would explain why CPU is still 100% even after the tab is closed - and I see the network requests go off in the worker as well on stackblitz - but I can never reproduce this locally.

Have you tried running this not through stackblitz @blanchg ?

**Comment by ntucker** [comment] 2019-06-15 16:59
I upped the chance of triggering by doing this:

```typescript
  const [issue1, issue] = useResource(
    [IssueResource.singleRequest(), { repositoryUrl: 'https://api.github.com/repos/facebook/react', number: 10 }],
    [IssueResource.singleRequest(), { repositoryUrl: 'https://api.github.com/repos/facebook/react', number: 11 }],
    [IssueResource.singleRequest(), { repositoryUrl: 'https://api.github.com/repos/facebook/react', number: 12 }],
    [IssueResource.singleRequest(), { repositoryUrl: 'https://api.github.com/repos/facebook/react', number: 13 }],
    [IssueResource.singleRequest(), { repositoryUrl: 'https://api.github.com/repos/facebook/react', number: 14 }],
  )
```

Was unable to reproduce by starting from homepage and waiting for page to load, then go to multiple page. However, I was able to freeze chrome every single time by hitting refresh *on* the multiple page. I think this is a race condition with the loading mechanism in stackblitz.

@blanchg are you able to reproduce *without* starting on 'multiple' page?

**Comment by ntucker** [comment] 2019-06-15 17:42
Able to consistently reproduce and track down what's happening: https://stackblitz.com/edit/rest-hooks-w44uh8?file=use%2Fuse.tsx

Refreshing on /multiple (or just saving to load the new code) will trigger it. It ends up calling `    console.log('computing', trigger.current, promises.length)` over and over - showing it's not actually memoizing the call.

Trying to see if react is just completely starting new components each time, but ref is behaving weirdly.

**Comment by blanchg** [comment] 2019-06-15 22:02
Thanks, I can reproduce locally which is what caused me to raise the issue
in the first place.

I can't remember it failing locally if I navigate to it but definitely if
it is refreshed. Funny thing is it will sometimes work even refreshing.

Thanks for tracking this down it is a nice feature to have!

**Comment by ntucker** [comment] 2019-06-15 23:58
```tsx
const networkManager = new NetworkManager();
render(<RestProvider manager={networkManager}><BrowserRouter><App /></BrowserRouter></RestProvider>, document.getElementById('root'));
```
fixed it for me.

I believe this might help you as well @jjordy.

I think what's happening is the provider is being reloaded by the hotreloader and so it's causing the manager to reset, which means the promises in flight never get resolved. Keeping the manager consistent seems to solve the issue.

I'll think about where to add a warning about this to the docs. Otherwise, I'm gonna close this for now - but feel free to re-open if you run into troubles again.

**Closed by ntucker** 2019-06-15 23:58 UTC
Labels: bug

**Comment by ntucker** [comment] 2019-06-16 04:28
I have confirmed that the degenerate case that was consistently reproducing (https://github.com/coinbase/rest-hooks/issues/78#issuecomment-502382704) has not been triggered in 1.6.6-beta.1 even without the workaround I posted above. Because of this I'll be releasing the new version with this fix :D

**Comment by blanchg** [comment] 2019-06-17 00:41
Thank you! this has fixed my use case  👍 Nice work
