### ISSUE TITLE
useStatefulResource throw "no provider error"

### ISSUE THREAD

**Issue by rtorrente** [coinbase/rest-hooks#1467] opened 2021-11-03 18:17 UTC
**React version** (e.g., 16.8.5) :  16.14.0

**Concurrent mode** no

**Rest Hooks version** 6.1.7

**Describe the bug**

useStatefulResource throw an error "It appears you are trying to use Rest Hooks without a provider.
Follow instructions: https://resthooks.io/docs/getting-started/installation#add-provider-at-top-level-component" but there is already a <CacheProvider> at the top of the app. 

The same request with a normal useResource works without any problem

**Expected behavior**

The request have to works when there is a <CacheProvider/> in the app

_Additionnal information : I'm not sure why this feature is in the legacy package as I am dealing with cases that require its use._

_For example if I'm looking to create a Guard component which try  to verify that a resource exists and that it has a particular property before showing the children. 
If the request fails or the property is not present, I need to call a function and redirect the user. Without useStatefullResource, I would have to create a specific ErrorBoundary, which will unnecessarily complicate the code. Maybe my usage could be done by another use that I did not understand?_

**Comment by ntucker** [comment] 2021-11-03 19:17
I suspect this is due to there being multiple copies of @rest-hook/core installed. Can you check yarn.lock or package-lock.json to see if this is true? If so you might try reinstalling like the instructions in 'caution' here https://resthooks.io/docs/upgrade/upgrading-to-6#package-compatibility

**Comment by ntucker** [comment] 2021-11-03 21:59
If you can get a minimum repo reproduction that would speed things up. I'm on the way to the airport and can see if I can replicate once I'm checked in

**Comment by ntucker** [comment] 2021-11-03 22:45
@rtorrente  Does the error get thrown in a test, or in browser?

**Comment by ntucker** [comment] 2021-11-03 23:25
What build system do you use webpack? if so which version. Also which version of node?

**Comment by ntucker** [comment] 2021-11-03 23:44
I tried reproducing this in a new project and could not. Can you maybe see about putting a CacheProvider *just* above the component calling useStatefulResource and see if that helps?

**Comment by rtorrente** [comment] 2021-11-03 23:55
Hmm I tried to reproduce in rapid code sandbox (https://codesandbox.io/s/festive-hawking-ypz2p) and I can't..

Problem seems to be on my app.

I will check tomorrow if I can get more details with Component Tree or Redux Rest-Hooks debug or find a resolution, it's night in France. I will post more details here.

Thanks and have a good flight !

**Comment by ntucker** [comment] 2021-11-23 13:44
I'm gonna pull useStatefulResource into the core package with a new name. This is blocked on figuring out a better name tho....

The new name for useResource is useSuspense....so useNotSuspense? lol. Would love input here.

**Comment by rtorrente** [comment] 2021-12-01 08:57
Hello @ntucker, sorry for the delay, I can't reproduce this bug on my app like in the sandbox, very strange.
Issue can be closed, sorry ..

It's a very good idea to put useStatefulResource in the core package. I think it's 2 option for using a resource (suspense or not) and two have their own use case.

Difficult for the name. The best would be useResource in my opinion but it would confuse the old one. Maybe useResponse, useRequest, useQuery or useData ? I'm not sure ...

**Closed** 2022-04-03 15:54 UTC
Labels: bug
