### ISSUE TITLE
Infinite scroll example

### ISSUE THREAD

**Issue by elsangedy** [coinbase/rest-hooks#128] opened 2019-09-03 21:02 UTC
Have some example to implement infinite scroll?

**Comment by ntucker** [comment] 2019-09-03 23:30
Best idea I've had so far is to use https://github.com/coinbase/rest-hooks/issues/96 to continually add pages to a common result list. If this seems reasonable for your use cases I'll write up an example after landing it.

Current work is here: https://github.com/coinbase/rest-hooks/tree/optimistic-update

**Comment by elsangedy** [comment] 2019-09-04 02:05
Good approach with optimistic update, I think can solve this use case

What do you think about? https://www.apollographql.com/docs/react/features/pagination/#using-fetchmore

**Comment by ntucker** [comment] 2019-09-04 05:17
Yeah that looks like an overly verbose, confusing and complicated version of the same principal - which is imperatively fetching the next results and having them be merged into an existing result set.

**Comment by ntucker** [comment] 2019-10-23 02:45
@elsangedy There's an example in here: https://github.com/coinbase/rest-hooks/pull/153 we haven't had the chance to fully test this though so we haven't updated the main docs. However, if you're able to get it working before us feel free to open a PR with a new page added under 'advanced' that shows an example for this. Thanks!

**Closed** 2020-03-04 02:43 UTC
Labels: enhancement

**Comment by ntucker** [comment] 2020-03-04 02:49
https://resthooks.io/docs/guides/infinite-scrolling-pagination

**Comment by stbn694** [comment] 2020-03-26 16:51
I followed the instructions in the docs almost exactly (only changed the cursor for an offset), but I can't get the results to append to the previous ones. I checked the two parameters passed to appendList, and they are both the same (the result of the last call). Any idea why this is happening?

**Comment by ntucker** [comment] 2020-03-26 19:43
Try inspecting the network traffic. I suspect you may be issuing the same fetch, instead of using the cursor parameter, which means you get the same results from the network.


The key part is here - the cursor parameter added after the params spread.

```ts
      return getNextPage({ ...params, cursor }, undefined, [
        // this instructs Rest Hooks to update the cache results specified by the first two members
        // with the merge algorithm of the third.
        [fetchShape, params, BaseResource.appendList],
      ]);
```

**Comment by stbn694** [comment] 2020-03-26 20:43
@ntucker No, the calls return fine. I get the first page and when I request the second one the results replace the previous, instead of being appended to them. And when I check which parameters the function appendList receives, both newResults and existingResults have the ids of the elements I got in the second page. That's the weird part.
I can show you a snippet of my code if you want, but it's practically identical to the docs.

**Comment by ntucker** [comment] 2020-03-29 20:24
@stbn694 That suggests that maybe your params are the same for both requests.

Here we are getting the `{}` params.

```ts
  const { results, cursor } = useResource(NewsResource.listShape(), {});
  const getNextPage = usePaginator(NewsResource.listShape(), {});
```

But the manual fetch we add cursor: `{ ...params, cursor }`

If this doesn't help then I'd probably have a better chance seeing the code.

**Comment by stbn694** [comment] 2020-03-30 07:02
@ntucker But if the params were the same, the request results would also be the same, right? But they are ok, the problem is that the second request override the first in the cache. Here is my code. It doesn't use TypeScript, but it should work, right?

AlertResource.js
```javascript
export default class PaginatedResource extends BaseResource {
  static listShape() {
    return {
      ...super.listShape(),
      getFetchKey: ({ start_index, ...params }) => {
        return super.listShape().getFetchKey(params);
      },
      schema: {
        elements: [this.asSchema()],
        has_more_elements: false,
        offset: 0
      }
    };
  }

  static appendList(newElements, existingElements) {
    const set = new Set([
      ...(existingElements?.elements ?? []),
      ...newElements.elements
    ]);
    return {
      ...newElements,
      elements: [...set.values()]
    };
  }
}
```

usePaginator.js
```javascript
export default function usePaginator(fetchShape, params) {
  const getNextPage = useFetcher(fetchShape, true);

  return useCallback(
    startIndex => {
      return getNextPage({ ...params, start_index: startIndex }, undefined, [
        [fetchShape, params, PaginatedResource.appendList]
      ]);
    },
    [getNextPage, params && fetchShape.getFetchKey(params)]
  );
}
```

AlertsList.js
```javascript
const AlertsList = ({ pageSize }) => {
  const { elements, has_more_elements, offset } = useResource(
    AlertResource.listShape(),
    {
      start_index: 0,
      count: pageSize
    }
  );
  const getNextPage = usePaginator(AlertResource.listShape(), {
    count: pageSize
  });

  return (
    <div>
      {alerts.map(alert => <div key={alert.id}>{alert.id}</div>)}
      {has_more_elements && (
        <Button onClick={getNextPage(offset)}>Load more</Button>
       )}
    </div>
  );
};
```

**Comment by ntucker** [comment] 2020-03-30 16:00
AlertResource.js
```ts
export default class PaginatedResource extends BaseResource {
  static listShape() {
    return {
      ...super.listShape(),
      schema: {
        elements: [this.asSchema()],
        has_more_elements: false,
        offset: 0
      }
    };
  }

  static appendList(newElements, existingElements) {
    const set = new Set([
      ...(existingElements?.elements ?? []),
      ...newElements.elements
    ]);
    return {
      ...newElements,
      elements: [...set.values()]
    };
  }
}
```

(usePaginator is fine)

AlertsList.js
```ts
const AlertsList = ({ pageSize }) => {
  const { elements, has_more_elements, offset } = useResource(
    AlertResource.listShape(),
    {
      count: pageSize
    }
  );
  const getNextPage = usePaginator(AlertResource.listShape(), {
    count: pageSize
  });

  return (
    <div>
      {alerts.map(alert => <div key={alert.id}>{alert.id}</div>)}
      {has_more_elements && (
        <Button onClick={() => getNextPage(offset)}>Load more</Button>
       )}
    </div>
  );
};
```

That should fix it assuming it's okay to have no index instead of 0.

This won't work, as you're now making all requests with different start indexes the same. This means it certainly cannot combine distinct requests because as far as its aware they are the same.
```ts
      getFetchKey: ({ start_index, ...params }) => {
        return super.listShape().getFetchKey(params);
      },
```

Instead we want to have the request without start_index be updated.
1) Render based on no start_index (hence `useResource(
    AlertResource.listShape(),
    {
      count: pageSize
    }
  )`)
2) Update that result using `[fetchShape, params, PaginatedResource.appendList]`. The params are lacking index_start, so they will match the params we are `useResource()` on

**Comment by ntucker** [comment] 2020-03-30 16:01
I'll think about maybe making a pagination generator since this is a fairly confusing set of things. Then I can reduce the interesting pieces to the data form rather than hookups.

**Comment by stbn694** [comment] 2020-03-30 16:13
@ntucker Yep, that did the trick. But I have a use case where the first request has to start already on index 40. So I would have the same problem. Any workarounds?

**Comment by ntucker** [comment] 2020-03-30 16:15
In that case you'll want to ensure you're reading from index 40 and inserting into index 40. 

Read from 40
```ts
useResource( AlertResource.listShape(), { start_index: 40, count: pageSize } );
```

Insert into 40
```ts
[fetchShape, { ...params, start_index: 40 }, PaginatedResource.appendList]
```

**Comment by stbn694** [comment] 2020-03-30 16:20
@ntucker Yes, it works! Thanks a lot! And that's how I wasted a whole week XD

**Comment by stbn694** [comment] 2020-03-30 16:24
Another question about pagination in general, not infinite scrolling, if you don't mind.
If I don't use infinite scrolling, each page will be stored in a different key in the cache, right? So what happens when I create a new element that would belong to the first page? Do I have to add it to the first page in the cache? And how are the next page updated, as all the results are moved one position?

**Comment by ntucker** [comment] 2020-03-30 16:34
This will probably become a lot more clear if you inspect the CacheProvider using react dev tools and look at the cache layout.

If you use [updateParams](https://resthooks.io/docs/api/useFetcher#updateparams-destshape-destparams-updatefunction) for your create that inserts it at the front, similar to how you built usePaginator(), then it will place it in the results that you `useResource()` on. This has all the ids of your pagination, so other pages will still be included and get 'pushed down one' as far as your view is concerned.

**Comment by stbn694** [comment] 2020-03-30 16:48
@ntucker OK, I think I got that. Now say my list of elements are returned ordered by timestamp, for example. When I use updateParams to include the new one in the cache, how do I now where to insert it, if I only have access to the IDs?

**Comment by ntucker** [comment] 2020-03-30 16:50
For that you'll have to sort after useresource.

**Comment by stbn694** [comment] 2020-03-30 16:53
@ntucker Hmm, I'll try that. Thanks for your time!

**Comment by uxxman** [comment] 2020-05-21 12:18
Hi @ntucker , I am trying to implement this infinite scroll example from docs, but getting error **Missing usable resource key when normalizing response.**.

While attempting to debug, the initial loading send item by item to the normalize function 
<img width="743" alt="Screen Shot 2020-05-21 at 14 13 11" src="https://user-images.githubusercontent.com/3153380/82558370-c65dd480-9b6d-11ea-9124-eefdbf71c898.png">

But the paginated next load sends the whole list to the normalize function instead of item by item
<img width="733" alt="Screen Shot 2020-05-21 at 14 13 32" src="https://user-images.githubusercontent.com/3153380/82558433-e42b3980-9b6d-11ea-945a-30cd5ce1a404.png">

**Comment by ntucker** [comment] 2020-05-21 12:58
@uxxman seems like a schema mismatch. What are the fetch shapes you're using?

**Comment by uxxman** [comment] 2020-05-21 13:09
Its pretty much the same as the example provided in docs

BaseResource.ts
```javascript
export default abstract class BaseResource extends Resource {
  static list<T extends typeof Resource>(this: T) {
    return {
      ...super.listShape(),
      schema: {
        items: [this.asSchema()],
        meta: {
          page: 1,
          nextPage: 0,
          prevPage: 0,
          totalPages: 1,
          totalItems: 1
        }
      }
    };
  }

  static appendList(
    newResults: {results: string[]},
    existingResults: {results: string[]} | undefined,
  ) {
    // In case there are duplicates, Set will eliminate them.
    const set = new Set([
      ...(existingResults?.results ?? []),
      ...newResults.results,
    ]);
    return {
      ...newResults,
      results: [...set.values()],
    };
  }
}
```

CategoryResource.ts
```javascript
export default class CategoryResource extends BaseResource {
  static urlRoot = 'http://test.com/categories';

  readonly id: number | undefined = undefined;

  readonly name: string = '';

  pk() {
    return this.id?.toString();
  }
}
```

Paginator.ts
```javascript
export default function usePaginator<
  S extends ReadShape<any, any>,
  P extends Omit<ParamsFromShape<S>, 'cursor'> | null
>(fetchShape: any, params: any) {
  // the second argument here is really important - it indicates that requests should be deduped!
  const getNextPage = useFetcher(fetchShape, true);

  return useCallback(
    (cursor: string) => {
      return getNextPage(
        {...params, page: cursor.meta.nextPage},
        undefined,
        [
          // this instructs Rest Hooks to update the cache results specified by the first two members
          // with the merge algorithm of the third.
          [fetchShape, params, BaseResource.appendList],
        ],
      );
      // "params && fetchShape.getFetchKey(params)" is a method to serialize params
    },
    [fetchShape, getNextPage, params],
  );
}
```

**Comment by ntucker** [comment] 2020-05-21 13:35
@uxxman can you show me where you're using usePaginator?

**Comment by uxxman** [comment] 2020-05-21 13:40
Yes sure

Sample Usage
```javascript
import React, {useState} from 'react';
import {Text} from 'react-native';
import {useResource} from 'rest-hooks';
import {CategoryResource} from '../resources';
import usePaginator from '../resources/paginator';

export default function Categories() {
  const [page, setPage] = useState(1);
  const {items: categories, meta} = useResource(CategoryResource.list(), {
    page,
    perPage: 5,
  });
  const getNextPage = usePaginator(CategoryResource.listShape(), {
    page,
    perPage: 5,
  });

  return (
    <>
      {categories.map((category) => (
        <Text key={category.name}>{category.name}</Text>
      ))}

      <Text onPress={() => getNextPage({meta})}>Load More...{page}</Text>
    </>
  );
}
```

**Comment by ntucker** [comment] 2020-05-21 13:42
CategoryResource.listShape() -> CategoryResource.list()


will fix methinks

**Comment by uxxman** [comment] 2020-05-21 14:06
Hey Using CategoryResource.list() fixed it 🙈nice catch. Thank you 😊 and great work with this library 👍

**Comment by ntucker** [comment] 2023-10-11 13:12
[Using pagination with the latest version](https://dataclient.io/rest/guides/pagination)
